python.md
To ensure we can update them in a backwards compatible way.
=> Add a new Python tip on calling Celery tasks

python.md
Add some guidance on effective flash messages.
=> Add section on flash messages

git.md
And include a link to my PR-crafting article.
=> Improve the git advice

python.md
This is something we want to do now.
=> Extend `CharField` section to suggest we namespace constants

python.md
Based on discussion here: https://github.com/octoenergy/styleguide/pull/8#pullrequestreview-132348929
=> Add section on not using audit fields for application logic

patterns.md
New page on patterns. First section explaining the motivation behind serializing template context.
=> Add new section on serializing template context

patterns.md
Which is worth documenting as it's slightly non-obvious.
=> Extend template-serializing section with details on non-list views

python.md
As per our conversation recently, updated the docs to clarify celery task definitions. I've also added some opinions about the way we specify queues, let me know what you think.
=> Clarified celery task guidance

patterns.md
- 3 layers (a quick summary)
- domain layer organisation
=> Expand patterns section with two new sections

python.md
To cover when to catch the base Exception class and how to handle it.
=> Extend notes on form_valid exception handling

python.md
To make it clearer that you can compute pre-conditions there.
=> Extend note on what is allowed in dispatch method

patterns.md
Just writing up some conventions that I've found useful.
=> Codify application layer conventions

python.md
As we have accumulated a mix of styles over the years and now mypy is
getting upset.
=> Add section on preferred style for __init__ imports

python.md
This isn't a major thing, but helps with the simplicity and readability
of the codebase.
=> Add para on locating exception classes

README.md, terraform.md
Extracted from https://github.com/octoenergy/conventions/pull/60
Credit to @gbergere.
=> Add first Terraform convention on SG rules

python.md
I see this pattern quite a bit and I think we should avoid it! What do people think?
=> Make function signatures explicit

terraform.md
Extracted from https://github.com/octoenergy/conventions/pull/60
=> Add Terraform convention on file naming

python.md
Fixes some spelling mistakes in the Python document.
=> Fix some typos

conventions/python.md
This PR moves 2 new conventions from Kraken handbook to the public conventions repo.
=> Move new immutable type conventions

.circleci/config.yml, .circleci/test_commits.py, makefile
To avoid accidentally leaving in fixup commits etc.
=> Validate commit subjects in CI

conventions/django.md
We agreed on a new convention last month not to add implicit ordering to models. The convention is duplicated in our public conventions.
=> Move new implicit ordering convention
